!
! Pifus is a library for overset grid assembly on parallel distributed systems
! Copyright (C) 2015 Jay Sitaraman
!
!>
!> Test code for Topology Independent Overset Grid Assembler (PIFUS)
!> 
!> Jay Sitaraman
!>
!> 03/05/2014
!>
program testPifus
  !
  use gridtype
  !
  implicit none
  !
  include 'mpif.h'
  !
  type(grid), target :: gr(2)
  type(grid), pointer :: g
  integer :: myid,numprocs,ierr,nsave
  integer :: itime,ntimesteps,iter,nsubiter
  real*8 :: t0
  integer :: blockid
  logical :: iclip
  integer :: ntypes
  integer :: nv1,nv2
  real*8 :: t1,t2
  integer :: i,n,m,ib,j
  real*8 :: xt(3),rnorm
  integer :: dcount,fcount
  integer, allocatable :: receptorInfo(:),inode(:)
  real*8, allocatable :: frac(:)
  !
  ! initialize mpi
  !
  call mpi_init(ierr)
  call mpi_comm_rank(mpi_comm_world,myid,ierr)
  call mpi_comm_size(mpi_comm_world,numprocs,ierr)
  !
  ! read grid based on that generated by the
  ! strand/Cart generator
  if (myid==0) write(6,*) '# pifus test on ',numprocs,' processes'
  call readGrid_cell(gr(1),myid)
  call readGrid_cell(gr(2),myid+numprocs)
  if (myid==0) write(6,*) '# pifus test : finished reading grids'  
  !
  nv1=6
  nv2=8  
  !
  call pifus_init()
  call pifus_use_timer()
  !
  do ib=1,2
     g=>gr(ib)
     if (g%n6 > 0) then
        call pifus_registergrid_data(ib,g%bodytag(1),g%c2f,g%face,&
             g%nfaces,g%nv,       &
             g%x,g%iblank_cell,   &
             g%nwbc,g%nobc,       &
             g%wbcnode,g%obcnode, &
             1,nv1,g%n6,g%ndc6)
     elseif (g%n8 > 0) then
        call pifus_registergrid_data(ib,g%bodytag(2),g%c2f,g%face,&
             g%nfaces,g%nv,       &
             g%x,g%iblank_cell,   &
             g%nwbc,g%nobc,       &
             g%wbcnode,g%obcnode, &
             1,nv2,g%n8,g%ndc8)        
     endif
  enddo
  call pifus_preprocess()
  call pifus_connect()
  call pifus_delete()
  !
  call mpi_finalize(ierr)
end program testPifus
